name: Debug
on:
  workflow_dispatch:
jobs:
  check-abi:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: System info
      run: lscpu; uname -a; zgrep -E 'IA32|X32|ABI' /proc/config.gz || grep -E 'IA32|X32|ABI' "/boot/config-$(uname -r)"
